site_name: microDocs - Laravel
# repo_url: https://github.com/jaimeranchal/ohdaw 
site_description: Notas rápidas sobre Laravel 8.x
site_author: Jaime Ranchal
dev_addr: '127.0.0.1:8001'

# Ajustes del tema
theme:
    logo: extra/img/favicon.ico
    favicon: extra/img/favicon.ico
    language: es
    name: material
    features:
        - navigation.tabs # 'tabs' en versiones más recientes
    palette:
        scheme: slate
        primary: red
        accent: lime
    font:
        text: Nunito
        code: Fira Code
    icon:
        logo: material/book-open-blank-variant

# Extensiones
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - def_list
    - pymdownx.details
    - pymdownx.highlight:
        use_pygments: false
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.snippets:
        base_path: '/home/jaime/Desarrollo/Docs/Laravel/docs/'
        check_paths: true
# Plugins
plugins:
    - search
    - print-site

# Extra
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/highlight.min.js
    - extra/js/blade.min.js
    - extra/js/config.js
extra_css:
    - extra/css/extra.css
    - extra/css/atom-one-dark.css
    # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/styles/atelier-lakeside-light.min.css
    # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/styles/atom-one-dark.min.css

# Árbol de documentos
nav:
    - Inicio: 'index.md'
    - 'Guía rápida':
        - Consola:
            - Composer: 'min/composer.md'  
            - Artisan: 'min/artisan.md'  
        - 'Modelo de datos':
            - Eloquent: 'min/eloquent.md'
            - Seeders: 'min/seeding.md'
        - Lógica:
            - Controladores: 'min/controller.md'
            - Middleware: 'min/middleware.md'
        - Interfaz: 
            - Vistas: 'min/views.md'
            - Rutas: 'min/rutas.md'
    - Ejemplos:
        - CRUD: 'examples/crud.md'
        - 'Inicio de sesión': 'examples/auth.md'
        - 'Zonas de usuario': 'examples/zones.md'
    - Documentación:
        - 'Inicio de sesión': 'full/auth.md'
        - 'Control de acceso': 'full/auto.md'
    - 'Base de datos': 'full/bbdd.md'
